spring.application.name=FoodApp

server.port = 9090

#mysql
spring.datasource.url = jdbc:mysql://localhost:3306/fooddb
spring.datasource.username = root
spring.datasource.password = Sagar@4006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update


#postgresql
#spring.datasource.url = jdbc:mysql://localhost:3306/fooddb
#spring.datasource.username = root
#spring.datasource.password = Sagar@4006
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialectc
#spring.jpa.hibernate.ddl-auto=update


#jwt key should be 30 characters or more
SecretJWTKey = F_@@_d1234_$$$$_5678_####_9101112_^^^_***_147852369009876543s21_saa

##Mail_Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password= app password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


